### ISSUE TITLE
fileContentsPredicate creation error caused by de-reference?

### ISSUE THREAD

**Issue by bassco** [OpsLevel/opslevel-go#448] opened 2024-08-08 14:23 UTC
Apologies for my lack of go coding experience  - using human pattern recognition here due to not being able to create a `opslevel_check_repository_search` resource. 

It looks like 2 of the `FileContentsPredicate` (de)references were missed?

https://github.com/OpsLevel/opslevel-go/blob/d75138cae18e055e0f184d30b60b9c6f3a8fc63f/input.go#L288
https://github.com/OpsLevel/opslevel-go/blob/d75138cae18e055e0f184d30b60b9c6f3a8fc63f/input.go#L343

If I compare it to: 

https://github.com/OpsLevel/opslevel-go/blob/d75138cae18e055e0f184d30b60b9c6f3a8fc63f/input.go#L255

**Comment by davidbloss** [comment] 2024-08-16 16:45
These two fields are not pointers by design. Details in [this thread](https://github.com/OpsLevel/opslevel-go/pull/449#issuecomment-2293825982) of linked PR.

Closing as a non-issue

**Closed by davidbloss** 2024-08-16 16:45 UTC
